export const REPORT_TEMPLATE_SYMBOLS = {
  REPORT_TEMPLATE_GENERATE_USE_CASE: 'REPORT_TEMPLATE_GENERATE_USE_CASE',
  DEVELOPER_REPORT_TEMPLATE_GENERATE_USE_CASE:
    'DEVELOPER_REPORT_TEMPLATE_GENERATE_USE_CASE',
};
