# Base stage for development and production
FROM node:22.8.0-slim AS base
WORKDIR /usr/api
COPY package.json package-lock.json ./
RUN npm install

# Development stage
FROM base AS development
EXPOSE 3000
EXPOSE 9229
CMD ["npm", "run", "dev"]